### ISSUE TITLE
Unable to use secretsmanager after version 0.3.2

### ISSUE THREAD

**Issue by raymonds-backyard** [boltops-tools/terraspace_plugin_aws#11]
Terraspace aws plugin version
0.3.3 (latest released)

Terraspace version
0.6.23 (latest released)

**What happened**
Deploying our stack which is dependent on the secret "<%= aws_secret("my-secret-here") %>".
This was working with our prior Terraspace aws plugin version of 0.3.0 and Terraspace version 0.6.13

This resulted in a NoMethodError: undefined method `[]' for nil:NilClass while evaluating ERB template for the secret.

**What you expected to happen**
The secret to be evaluated correctly with the role defined in config/terraform/providers.tf

Reproducible by planning any stack that utilises the aws_secret helper.

**Comment by tongueroo** [comment]
Thanks for the report. Resolved this with #14.
