### ISSUE TITLE
Unable to add tags to AWS backend table and s3 bucket

### ISSUE THREAD

**Issue by rjcoelho** [boltops-tools/terraspace_plugin_aws#7]
All my resources need to be tagged. i'm probably not the only one.
Can you help me on how to do this ?
Thanks

**Comment by tongueroo** [comment]
Transferred the issue to https://github.com/boltops-tools/terraspace_plugin_aws

**Comment by tongueroo** [comment]
Noting: The create_bucket call is here https://github.com/boltops-tools/terraspace_plugin_aws/blob/master/lib/terraspace_plugin_aws/interfaces/backend/bucket.rb#L17

Looks like the AWS API create_bucket call does not take a list of tags: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#create_bucket-instance_method

So will probably have to call the tagging api afterwards.
